app1/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', LoginView, name='LoginView'),
    path('dashboard/', Dashboard, name='Dashboard'),
    path('View_Bills/<str:ids>', SK_View_Bills, name='SK_View_Bills'),
    path('SK_create_pdf/<str:dt>', SK_Create_Pdf, name='sk_create_pdf'),
    path('addproduct/', AddProduct, name='AddProduct'),
    path('productlist/', ProductListView, name='ProductListView'),
    path('deleteproduct/<int:id>', DeleteProduct, name='DeleteProduct'),
    path('editproduct/<int:id>', EditProduct, name='EditProduct'),
    path('addsales/', AddSaleView, name='AddSaleView'),
    path('saleslist/', SalesListView, name='SalesListView'),
    path('salesdelete/<int:id>', SalesDelete, name='SalesDelete'),
    path('logoutstore/', LogoutStore, name='LogoutStore'),
    path('profile/', profileview, name='profile'),
    path('adminregister/', Adminregister, name='Adminregister'),
    path('adminlogin/', Adminlogin, name='Adminlogin'),

    path('admin_SK_create_pdf/<str:dt>',
         admin_SK_Create_Pdf, name='admin_sk_create_pdf'),
    # Forget Password -----------
    path('forgotpass/', forgot_pass, name='forgotpass'),
    path('otpcheck/', otpcheck, name='otpcheck'),
    path('newpassword/', newpassword, name='newpassword'),
    # Forget Password -----------
    path('admindashboard/', AdminDashboard, name='AdminDashboard'),
    path('storedelete/<int:id>', deletestore, name='deletestore'),
    path('storeview/<int:id>', viewstore, name='viewstore'),
    path('storeedit/<int:id>', editstore, name='editstore'),
    path('addstore/', addstore, name='addstore'),
    path('addstock/', addstock, name='addstock'),
    path('viewstock/', viewstock, name='viewstock'),
    path('editstock/<int:id>', editstock, name='editstock'),
    path('accept_data/<int:sk>/<int:id>/', accepteddata, name='accept_data'),
    path('denied_data/<int:sk>/<int:id>/', denieddata, name='denied_data'),
    path('salefilter/', SalefilterView, name='SalefilterView'),
    path('storesales/', GraphCall, name='storesales'),
    path('monthsale/', monthsaleview, name='monthsaleview'),
    path('adminlogout/', adminlogout, name='adminlogout'),
    path('totallist/', totallistview, name='totallistview'),
    path('todaylist/', todaylistview, name='todaylistview'),
    path('Confirm_Orders/', Confirm_Orders, name="confirm_order"),
    path('billdata/<str:dt>', billdata, name='billdata'),
    path('Order_Bills_data/', Order_Bills_data, name='Order_Bills_data'),
    # HTml To PDF -------------
    path('create_pdf/<str:dt>', Create_Pdf, name='create_pdf'),

]

salesprediction/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls'))
]

app1/models.py
from django.db import models

class StoreDetails(models.Model):
    StoreName = models.CharField(max_length = 50,blank = True)
    PersonName = models.CharField(max_length = 50,blank = True)
    Contact = models.IntegerField(blank = True)
    email = models.EmailField(blank = True, default="", max_length=150)
    password = models.CharField(max_length = 50)
    add1 = models.TextField(default="")

    def __str__(self):
        return self.StoreName


class StockDetails(models.Model):
    # admin_nm = models.ForeignKey('adminregi',on_delete=models.CASCADE, null=True)
    email = models.ForeignKey('adminregi',on_delete=models.CASCADE, null = True)
    productName = models.CharField(max_length = 50,blank = True)
    #PersonName = models.CharField(max_length = 50,blank = True)
    quantity = models.IntegerField()
    price = models.IntegerField()

    def __str__(self):
        return self.productName

    #email = models.EmailField(blank = True, unique = True)
    #password = models.CharField(max_length = 50)


class SK_Bills(models.Model):
    store_person = models.ForeignKey('StoreDetails',on_delete=models.CASCADE, null=True)
    Bill_No = models.CharField(max_length = 200,default="")
    pd_nm = models.CharField(max_length = 200,default="")
    pd_price = models.FloatField(default=0.0)
    pd_qty = models.IntegerField(default=0)
    pd_tot = models.FloatField(default=0.0)
    date_data = models.DateField(auto_now=False,blank=True,null=True)
    
    def __str__(self):
        return self.Bill_No


class ProductDetails(models.Model):
    store_person = models.ForeignKey('StoreDetails',on_delete=models.CASCADE, null=True)
    productname = models.CharField(max_length = 50,default="")
    productquantity = models.IntegerField()
    date = models.DateField(auto_now=False,blank=True,null=True)
    status = models.BooleanField(default=False)
    isDeny = models.BooleanField(default=False)
    Bills_id = models.CharField(max_length = 200,default="",null=True,blank=True)

    def __str__(self):
        return self.productname

class SalesDetails(models.Model):
    productname = models.CharField(max_length = 50)
    qty = models.IntegerField()
    date = models.CharField(max_length = 50,blank = True)
    totalprice = models.CharField(max_length = 50, blank = True)

class FilterDate(models.Model):
    filterdataDate = models.CharField(max_length = 50,blank = True)

class profilemodel(models.Model):
    firstname= models.CharField(max_length=100)
    email = models.EmailField(max_length=100,default='')
    mobileno = models.PositiveIntegerField(default='')
    address = models.TextField(max_length=1000,default='')
    store = models.CharField(max_length=100)
#=====================ADMIN=============>
class adminregi(models.Model):
    admin_nm = models.CharField(max_length = 50,unique = True)
    email = models.EmailField(blank = True ,default='',max_length=100,unique=True)
    password1 = models.CharField(max_length = 50)
    password2 = models.CharField(max_length = 50)

    def __str__(self):
        return self.email


class SaleFilter(models.Model):
    ProductName = models.CharField(max_length = 50,blank = True)

app1/forms.py
from django import forms
from .models import StoreDetails,ProductDetails,SalesDetails,FilterDate,StockDetails,profilemodel

#=============Admin=========>
from .models import adminregi
#<===========================

class StoreDetailsForm(forms.ModelForm):
    class Meta:
        model = StoreDetails
        fields = '__all__'

class StockDetailsForm(forms.ModelForm):
    class Meta:
        model = StockDetails
        fields = '__all__'


class ProductDetailsForm(forms.ModelForm):
    class Meta:
        model = ProductDetails
        fields = '__all__'

class SalesDetailsForm(forms.ModelForm):
    class Meta:
        model = SalesDetails
        fields = '__all__'

class FilterDateForm(forms.ModelForm):
    class Meta:
        model = FilterDate
        fields = '__all__'

class profileform(forms.ModelForm):
    class Meta:
        model = profilemodel
        fields = '__all__'
#=============Admin=========>

class adminregform(forms.ModelForm):
    class Meta:
        model = adminregi
        fields = '__all__'

app1/views.py
from json import dumps
from datetime import datetime, timezone
from django.shortcuts import render, redirect, get_object_or_404
from .models import StoreDetails, ProductDetails, SalesDetails, FilterDate, StockDetails, profilemodel, SK_Bills
from .forms import ProductDetailsForm, SalesDetailsForm, FilterDateForm, StoreDetailsForm, StockDetailsForm, profileform
from django.http import HttpResponse, HttpResponseRedirect
from datetime import date
import datetime
import pytz
import time
from django.contrib import messages
from django.db.models import Q

# email ---------
import smtplib
import email.message
from smtplib import SMTP

import random

from django.conf import settings

# Html To Pdf -------------------

from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template

from xhtml2pdf import pisa

from django.http import HttpResponse
from django.views.generic import View

#import pdfkit

# Html To Pdf -------------------

from sklearn.linear_model import LinearRegression

# ===============ADMIN=================>
from .models import adminregi, SaleFilter, SK_Bills
from .forms import adminregform
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# <====================================
def LoginView(request):
    if request.method == 'POST':
        try:
            obj = StoreDetails.objects.get(email=request.POST['email'])
            if obj.password == request.POST['password']:
                request.session['username'] = obj.email

                return HttpResponseRedirect('/dashboard/')

            else:
                # return HttpResponse("Incorrect Password")
                messages.warning(request, message="Invalid  Password!")
                return render(request, 'store/login.html')

        except:
            # return HttpResponse("Invalid username")
            messages.warning(request, message="Invalid Email!")
            return render(request, 'store/login.html')

    return render(request, 'store/login.html')


class ProductViewData():
    def __init__(self, name, date, status):
        self.name = name
        self.date = date
        self.status = status

def getStatusInStr(isStatus, isDeny):
    if isStatus == True:
        return "Accepted"
    else:
        if isDeny == True:
            return "Denied"
        return "Pending"

def Dashboard(request):
    if request.session.has_key('username'):
        username = request.session['username']
        store = StoreDetails.objects.get(email=username)

        pdBill = SK_Bills.objects.filter(store_person=store)
        Bcount = 0
        bset = set()
        for i in pdBill:
            bset.add(str(i.Bill_No))

        print(bset)
        bset = list(bset)
        # bset.sort()
        print(bset)

        model = ProductDetails.objects.filter(store_person=store).count()
        today_stock = ProductDetails.objects.filter(
            store_person=store, date=date.today())
        qty = 0
        today_date = date.today
        print(today_date)

        acceptedData = ProductDetails.objects.filter(store_person=store)
        acceptedData = map(lambda product: ProductViewData(getattr(product, 'productname'), getattr(product, 'date'), getStatusInStr(getattr(product, 'status'), getattr(product, 'isDeny'))), acceptedData)

        for i in today_stock:
            qty += i.productquantity
        return render(request, 'store/dashboard.html', {'acceptedData' : acceptedData, 'bset': bset, 'Bcount': len(bset), 'data': model, 'total': qty, 'date': today_date, 'username': username})
    else:
        return redirect('LoginView')


def SK_View_Bills(request, ids):
    pdBill = SK_Bills.objects.filter(Bill_No=ids)
    tot = 0.0
    date = ""
    sperson = ''
    for i in pdBill:
        date = i.date_data
        sperson = i.store_person
        tot += float(i.pd_tot)
    return render(request, 'store/SK_Order_Bill.html', {'billNo': ids, 'sperson': sperson, 'ddate': date, 'tot': tot, 'BillDes': pdBill})


def SK_render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None


def SK_Create_Pdf(request, dt):
    if request.session.has_key('username'):
        username = request.session['username']
        store = StoreDetails.objects.get(email=username)
        pdBill = SK_Bills.objects.filter(Bill_No=dt)
        tot = 0.0
        date = ""
        sperson = ''
        for i in pdBill:
            date = i.date_data
            sperson = i.store_person
            tot += float(i.pd_tot)
        Order_Data = {}
        obj_data = SK_Bills.objects.filter(Bill_No=dt)
        prod_price = 0
        prod_qty = 0
        qty = 0
        new = {}
        grand_tot = 0
        for i in obj_data:
            recd_data = {}
            recd_data["prod_price"] = i.pd_tot
            grand_tot += i.pd_tot
            recd_data["prod_qty"] = i.pd_qty
            recd_data['real_price'] = i.pd_price
            new[str(i.pd_nm)] = recd_data
        Order_Data[store] = new

        data = {'data': Order_Data, 'grand_tot': grand_tot}

        pdf = render_to_pdf('admin/Create_Pdf.html', data)
        return HttpResponse(pdf, content_type='application/pdf')
    else:
        return redirect('LoginView')


def GraphCall(request):
    model = StoreDetails.objects.all()
    sk_nm = []
    for i in model:
        sk_nm.append(str(i.StoreName))
    tots = []
    for i in sk_nm:
        std = StoreDetails.objects.get(StoreName=i)
        sk = SK_Bills.objects.filter(store_person=std)
        vals = 0
        for j in sk:
            vals += float(j.pd_qty)
        tots.append(vals)
    print(sk_nm)
    print(tots)
    data = {}

    for i in range(len(sk_nm)):
        data[tots[i]] = sk_nm[i]
    print(data)
    # data = dumps(data)
    return render(request, 'admin/grap.html', {'data': data, 'sks': sk_nm, 'tots': tots})


def Confirm_SK_Orders(request):
    if request.session.has_key('username'):
        username = request.session['username']
        SD = StoreDetails.objects.get(email=username)
        print("======================")
        print(SD)
        Order_Data = {}

        obj_data = ProductDetails.objects.filter(status=True, store_person=SD)

        prod_price = 0
        prod_qty = 0
        qty = 0
        new = {}
        grand_tot = 0
        for i in obj_data:
            recd_data = {}
            print(i)
            qty += 1
            print(qty)

            prod_qty += int(i.productquantity)
            print(prod_qty)

            data = StockDetails.objects.get(productName=i.productname)
            print(data, i.productquantity)
            print(data.price)
            rec = float(data.price * i.productquantity)
            print(rec)
            prod_price += rec
            print(prod_price)

            print("=============")
            # recd_data['prod_nm'] = data
            recd_data["prod_price"] = prod_price
            grand_tot += prod_price
            recd_data["prod_qty"] = prod_qty
            recd_data['real_price'] = data.price
            new[str(data.productName)] = recd_data
            print(new)
        Order_Data[SD] = new
        print(Order_Data)
        print("======================")

        return render(request, 'store/SK_Order_Bill.html', {'data': Order_Data, 'grand_tot': grand_tot})
    else:
        return redirect('LoginView')


def AddProduct(request):
    if request.session.has_key('username'):
        username = request.session['username']
        store = StoreDetails.objects.get(email=username)
        prods = StockDetails.objects.all()
        if request.POST:
            pro_data = request.POST['productname']
            pro_qty = request.POST['productquantity']

            obj = ProductDetails()
            obj.store_person = store

            pro_nm = StockDetails.objects.get(id=int(pro_data))

            obj.productname = pro_nm.productName
            obj.productquantity = pro_qty
            obj.save()

        # form = ProductDetailsForm(request.POST)
        # if form.is_valid():
        #     form.save()
            return redirect('/productlist/')
        return render(request, 'store/addproduct.html', {'username': username, 'prods': prods})
    else:
        return redirect('LoginView')


def DeleteProduct(request, id):
    if request.session.has_key('username'):
        username = request.session['username']
        obj = ProductDetails.objects.get(id=id)
        obj.delete()
        return redirect('/productlist/', {'username': username})
    else:
        return redirect('LoginView')


def EditProduct(request, id):
    if request.session.has_key('username'):
        username = request.session['username']
        model = ProductDetails.objects.get(id=id)
        # form = ProductDetailsForm(request.POST, instance=model)
        if request.POST:
            model.productname=request.POST['productname']
            model.productquantity=request.POST['productquantity']
            model.save()
            return redirect('/productlist/')
        return render(request, 'store/editproduct.html', {'data': model, 'username': username})
    else:
        return redirect('LoginView')


def ProductListView(request):
    if request.session.has_key('username'):
        username = request.session['username']
        store = StoreDetails.objects.get(email=username)
        model = ProductDetails.objects.filter(store_person=store)
        return render(request, 'store/productlist.html', {'data': model, 'username': username})
    else:
        return redirect('LoginView')


def AddSaleView(request):
    if request.session.has_key('username'):
        username = request.session['username']
        model = ProductDetails.objects.all()

app1/templates/store/SK_Order_Bill.html
{% extends 'store/base.html' %}
{% block content_data %}


<h2 align="center">Bill No : {{ billNo }}</h2>
<br> <br>
<h2 align="center"> Date : {{ ddate }}</h2>

<br><br>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Bill Details</h4>
   
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th style="text-align: center;font-weight: bold;"> No. </th>
                <th style="text-align: center;font-weight: bold;"> Product Name </th>
                <th style="text-align: center;font-weight: bold;"> Product Price </th>
                <th style="text-align: center;font-weight: bold;"> Product QTY </th>
                <th style="text-align: center;font-weight: bold;">Product Total</th>
              </tr>
            </thead>
            <tbody>

                {% for i in BillDes %}
                <tr>
                    <td style="text-align: center;" >{{ forloop.counter }}</td>
                    <td style="text-align: center;">{{ i.pd_nm }}</td>
                    <td style="text-align: center;">{{ i.pd_price }}</td>
                    <td style="text-align: center;">{{ i.pd_qty }}</td>
                    <td style="text-align: center;">{{ i.pd_tot }}</td>
                </tr>
     
            {% endfor %}
            <tr>
                <td style="font-weight: bold;" >Payable Amount </td>
                <h4><td>{{ tot }}</td></h4>
            </tr>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<td> <div style="margin-left:15%;">
    <a style="margin-left:45%;" class="btn btn-info" href="{% url 'sk_create_pdf' billNo %}"> View Bill </a>
   </div>
</td>
</table>
</h3>

{% endblock content_data %}

app1/templates/store/addproduct.html
{% extends 'store/base.html' %}
{% block content_data %}
<center>
  
    <h1>Add Medicines</h1><br>
<form method="POST" onsubmit="alert('Product Added successfully');">
    {% csrf_token %}
    <!-- <div class="form-group">
      
      <input type="text" placeholder="Enter Product Name" class="form-control" name="productname" id="id_productname" style="width: 40%;">
    </div> -->
    <div class="form-group">
      
      <!-- <input type="text" placeholder="Enter Product Name" class="form-control" name="productname" id="id_productname" style="width: 40%;"> -->
        <select name="productname" style="width: 40%; ">
        {% for i in prods %}
        <option value="{{ i.id }}"> {{ i.productName }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <input type="number" placeholder="Enter Medicine quantity" class="form-control" name="productquantity" id="id_productquantity" style="width: 40%;">
    </div>
    
    <button type="submit" class="btn btn-success">Add medicine</button>
  </form> </center>

{% endblock content_data %}

app1/templates/store/editproduct.html
{% extends 'store/base.html' %}
{% block content_data %}
<center>
    <h1>Edit Product</h1><br>
<form method="POST" onsubmit="alert('Product Edit successfully');">
    {% csrf_token %}
    <div class="form-group">
      
      <input type="text" placeholder="Enter Product Name" class="form-control" name="productname" id="id_productname" style="width: 40%;" value="{{ data.productname }}">
    </div>
    <div class="form-group">
      
      <input type="number" placeholder="Enter Product Quantity" class="form-control" name="productquantity" id="id_productquantity" style="width: 40%;" value="{{ data.productquantity }}">
    </div>
    
    <button type="submit" class="btn btn-success">Edit Medicine</button>
  </form> </center>

{% endblock content_data %}

app1/templates/store/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Organization Stocks </title>
  <!-- base:css -->
  <link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/base/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-stretch auth auth-img-bg">
        <div class="row flex-grow">
          <div class="col-lg-6 d-flex align-items-center justify-content-center">
            <div class="auth-form-transparent text-left p-3">
          
              <h4>Welcome To </h4>
              <h3 class="font-weight-light">Pharmacist Panel</h3>
              <form class="pt-3" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="exampleInputEmail">Email ID</label>
                  <div class="input-group">
                    <div class="input-group-prepend bg-transparent">
                      <span class="input-group-text bg-transparent border-right-0">
                        <i class="mdi mdi-account-outline text-primary"></i>
                      </span>
                    </div>
                    <input type="email" class="form-control form-control-lg border-left-0" id="id_email" name='email' placeholder="Email Id">
                  </div>
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword">Password</label>
                  <div class="input-group">
                    <div class="input-group-prepend bg-transparent">
                      <span class="input-group-text bg-transparent border-right-0">
                        <i class="mdi mdi-lock-outline text-primary"></i>
                      </span>
                    </div>
                    <input type="password" class="form-control form-control-lg border-left-0" id="id_password" name="password" placeholder="Password">                        
                  </div>
                </div>
                
                <div class="my-3">
                  <input type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" value="LOGIN">
                </div>
                
                
              </form>
            
              <div class="my-2 d-flex justify-content-between align-items-center">
                  
                <a href="{% url 'Adminlogin' %}" class="auth-link text-black">Supplier Login</a>
              </div>
        
            </div>
          </div>
          <div class="col-lg-6 login-half-bg d-flex flex-row">
            <p class="text-white font-weight-medium text-center flex-grow align-self-end">Copyright &copy; 2022  All rights reserved.</p>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- base:js -->
  <script src="{% static 'vendors/base/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="{% static 'js/template.js' %}"></script>
  <!-- endinject -->
  <!-- plugin js for this page -->
  <!-- End plugin js for this page -->
  <!-- Custom js for this page-->
  <!-- End custom js for this page-->
</body>

</html>

app1/templates/store/profile.html
{% extends 'store/base.html' %}
{% load static %}
{% block content_data %}
<html>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
  <label for="fname">Name</label>
  <input type="text" id="id_PersonName" class="form-control" name="PersonName" value="{{ shop.PersonName }}" placeholder="Your name.."><br>
</div>
<div  class="form-group" class="col-md-12">
  <label for="email">Email</label>
  <input type="email" id="id_email"class="form-control"  name="email"  value="{{ shop.email }}" placeholder="Your email.."><br>
</div>
<div class="form-group" class="col-md-12">
  <label for="mobile">Mobile No</label>
  <input type="number" id="id_Contact" class="form-control" name="Contact" value="{{ shop.Contact }}" placeholder="Your mobile no.."><br>
  
<div class="form-group" class="col-md-12">
  <label for="address">Address</label>
  <input type="text" id="id_add1" class="form-control" name="add1" value="{{ shop.add1 }}" placeholder="Your address.."><br>
</div>
<div class="form-group" class="col-md-12">

  <label for="store">Pharmacist Name</label>
  <input type="text" id="id_StoreName" class="form-control" name="StoreName" value="{{ shop.StoreName }}" placeholder="Your store name.."><br>
</div>

  <input type="submit" value="Save Change"><br>
</form>
</div>
</div>
</div>

</body>
</html>
{% endblock content_data %}

app1/templates/store/sales.html
{% extends 'store/base.html' %}
{% block content_data %}
<center>
    <h1>Add medicines Record</h1><br>
<form method="POST" onsubmit="alert('Sales Added successfully');">
    {% csrf_token %}
    <div class="form-group">
      
      <select name="productname" id="id_productname" style="width: 40%;">
          {% for i in data %}
          <option value="{{ i.productname }}">{{ i.productname }}</option>
          {% endfor %}
      </select>
    </div>
    <div class="form-group">
      
      <input type="number" placeholder="Enter Quantity" class="form-control" name="qty" id="id_qty" style="width: 40%;">
    </div>
    <div class="form-group">
      
        <input type="date" class="form-control" name="date" id="id_date" style="width: 40%;">
      </div> 
    
    <button type="submit" class="btn btn-success">Add Sales</button>
  </form> </center>

{% endblock content_data %}